directories:
  output: dist-electron
  buildResources: build
appId: com.goldease.receipt
productName: Gold Ease Receipt
files:
  - filter:
      - dist/**/*
      - electron/main.js
win:
  target: nsis
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
publish: null
electronVersion: 37.3.1
